### ISSUE TITLE
is_patched is broken

### ISSUE THREAD

**Issue by oaken-source** [HearthSim/python-mpq#2]
trying to invoke is_patched on an MPQFile instance yields:

`NameError: name 'name' is not defined`

which is not surprising, given the code in question:

```
    def is_patched(self):
        """
        Returns whether at least one of the archives in the MPQFile has been patched.
        """
        for mpq in self._archives:
            if storm.SFileIsPatchedArchive(mpq, name):
                return True
        return False
```

there is no `name` in that scope.

**Comment by jleclanche** [comment]
¯\\\_(ツ)\_/¯
I'll merge a PR if you can make one; MPQs being essentially gone, this project is unmaintained right now.

**Comment by oaken-source** [comment]
thanks for keeping the project around anyway - mpqs are still useful for reverse engineering old game engines :)
